"""
This module outlines all possible system actions that can be generated by the language model
and executed by the host agent. 

To support constrained JSON decoding via outlines, all model structures strictly follow
Pydantic BaseModel definitions, wrapping action-specific parameters inside a nested 'params' block.

Technical Specifications:
- Models subclass Pydantic's BaseModel for automated schema generation and serialization.
- Literals (using typing.Literal) define fixed app and action names.
- Optional parameters are explicitly annotated with default values of None.

================================================================================
ACTION TO TRANSLATOR BRIDGE REFERENCE MAP
================================================================================
Each action class in this file is mapped to a corresponding translation function
in src/bridge.py, which converts Pydantic fields into macOS executable scripts:

Finder Actions (src/bridge.py):
- FinderOpen                     => translate_finder_open()
- FinderClose                    => translate_finder_close()
- FinderEmptyTrash               => translate_finder_empty_trash()
- FinderGetActiveWindowPath      => translate_finder_get_active_window_path()
- FinderCreateFolder             => translate_finder_create_folder()

System Actions (src/bridge.py):
- SystemSetVolume                => translate_system_set_volume()
- SystemUpdateVolume             => translate_system_update_volume()
- SystemSetBrightness            => translate_system_set_brightness()
- SystemUpdateBrightness         => translate_system_update_brightness()
- SystemReadVolume               => translate_system_read_volume()
- SystemHideApps                 => translate_system_hide_apps()
- SystemEjectDisks               => translate_system_eject_disks()
- SystemToggleDarkMode           => translate_system_toggle_dark_mode()
- SystemSleep                    => translate_system_sleep()
- SystemShutDown                 => translate_system_shutdown()
- SystemRestart                  => translate_system_restart()
- SystemLockScreen               => translate_system_lock_screen()

Safari Actions (src/bridge.py):
- SafariOpen                     => translate_safari_open()
- SafariClose                    => translate_safari_close()
- SafariNewTab                   => translate_safari_new_tab()
- SafariCloseTab                 => translate_safari_close_tab()
- SafariGetActiveTabURL          => translate_safari_get_active_tab_url()
- SafariGetActiveTabTitle        => translate_safari_get_active_tab_title()
- SafariNavigateTab              => translate_safari_navigate_tab()
- SafariRefreshPage              => translate_safari_refresh_page()

Chrome Actions (src/bridge.py):
- ChromeOpen                     => translate_chrome_open()
- ChromeClose                    => translate_chrome_close()
- ChromeNewTab                   => translate_chrome_new_tab()
- ChromeCloseTab                 => translate_chrome_close_tab()
- ChromeGetActiveTabURL          => translate_chrome_get_active_tab_url()
- ChromeNavigateTab              => translate_chrome_navigate_tab()
- ChromeRefreshPage              => translate_chrome_refresh_page()
- ChromeOpenNewWindow            => translate_chrome_open_new_window()

Apple Music Actions (src/bridge.py):
- AppleMusicOpen                 => translate_apple_music_open()
- AppleMusicClose                => translate_apple_music_close()
- AppleMusicTrackChange          => translate_apple_music_change_track()
- AppleMusicTogglePlayback       => translate_apple_music_toggle_playback()
- AppleMusicGetPlayingSongDetails=> translate_apple_music_get_playing_song_details()
- AppleMusicAddToFavorites       => translate_apple_music_add_to_favorites()
- AppleMusicRemoveFromFavorites  => translate_apple_music_remove_from_favorites()
- AppleMusicShuffle              => translate_apple_music_shuffle()
- AppleMusicRepeat               => translate_apple_music_repeat()

Spotify Actions (src/bridge.py):
- SpotifyOpen                    => translate_spotify_open()
- SpotifyClose                   => translate_spotify_close()
- SpotifyTrackChange             => translate_spotify_change_track()
- SpotifyTogglePlayback          => translate_spotify_toggle_playback()
- SpotifyGetPlayingSongDetails   => translate_spotify_get_playing_song_details()
- SpotifyShuffle                 => translate_spotify_shuffle()
- SpotifyRepeat                  => translate_spotify_repeat()
- SpotifySearchAndPlay           => translate_spotify_search_and_play()

Notes Actions (src/bridge.py):
- NotesOpen                      => translate_notes_open()
- NotesClose                     => translate_notes_close()
- NotesGetNotes                  => translate_notes_get_notes()
- NotesCreateNote                => translate_notes_create_note()
- NotesGetNoteContent            => translate_notes_get_note_content()
- NotesAddToNote                 => translate_notes_update_note()

Calendar Actions (src/bridge.py):
- CalendarOpen                   => translate_calendar_open()
- CalendarClose                  => translate_calendar_close()
- CalendarGetEvents              => translate_calendar_get_events()
- CalendarCreateEvent            => translate_calendar_create_event()
- CalendarUpdateEvent            => translate_calendar_update_event()
- CalendarReadEvent              => translate_calendar_read_event()

Reminders Actions (src/bridge.py):
- RemindersOpen                  => translate_reminders_open()
- RemindersClose                 => translate_reminders_close()
- RemindersGetReminders          => translate_reminders_get_reminders()
- RemindersCreateReminder        => translate_reminders_create_reminder()
- RemindersUpdateReminder        => translate_reminders_update_reminder()
- RemindersDeleteReminder        => translate_reminders_delete_reminder()

TextEdit Actions (src/bridge.py):
- TextEditOpen                   => translate_textedit_open()
- TextEditClose                  => translate_textedit_close()
- TextEditNewDocument            => translate_textedit_new_document()
- TextEditOpenDocument           => translate_textedit_open_document()

Router Actions (src/bridge.py):
- RouterDoNothing                => translate_router_do_nothing()
- RouterLlmAgent                 => translate_router_llm_agent() [SKIPPED FOR NOW]
"""

# Import the typing library's Optional wrapper to declare fields that can accept either None or their nominal types at runtime
from typing import Optional

# Import Pydantic base classes and field objects to build metadata structures and handle automatic deserialization validation
from pydantic import BaseModel, Field

# Import Literal mapping type to define strict string value checks and Union type for handling polymorphic schemas
from typing import Union, Literal

# Schema definition representing empty parameter namespaces for commands that execute without inputs
class EmptyParams(BaseModel):
    """
    Represents an empty parameters model for system actions that require no arguments.
    """
    # Empty block placeholder acting as a formal structure parameter mapping for zero-argument routing commands
    pass

# ==========================================
# FINDER ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'finder.open' structured actions
class FinderOpen(BaseModel):
    """
    Main action routing model for finder.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["finder"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'finder.close' action constraints
class FinderCloseParams(BaseModel):
    """
    Parameter schema for action finder.close.
    """
    # Parameter attribute validation constraint field mapping for incoming 'scope' arguments
    scope: Literal["all", "current"]

# Main action routing class definition mapping for parsing 'finder.close' structured actions
class FinderClose(BaseModel):
    """
    Main action routing model for finder.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["finder"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: FinderCloseParams

# Main action routing class definition mapping for parsing 'finder.empty_trash' structured actions
class FinderEmptyTrash(BaseModel):
    """
    Main action routing model for finder.empty_trash.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["finder"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["empty_trash"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'finder.get_active_window_path' structured actions
class FinderGetActiveWindowPath(BaseModel):
    """
    Main action routing model for finder.get_active_window_path.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["finder"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_active_window_path"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'finder.create_folder' action constraints
class FinderCreateFolderParams(BaseModel):
    """
    Parameter schema for action finder.create_folder.
    """
    # Parameter attribute validation constraint field mapping for incoming 'location' arguments
    location: str
    # Parameter attribute validation constraint field mapping for incoming 'name' arguments
    name: str

# Main action routing class definition mapping for parsing 'finder.create_folder' structured actions
class FinderCreateFolder(BaseModel):
    """
    Main action routing model for finder.create_folder.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["finder"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["create_folder"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: FinderCreateFolderParams


# ==========================================
# SYSTEM ACTIONS
# ==========================================
# Declaration of parameter namespace schema class for 'system.set_volume' action constraints
class SystemSetVolumeParams(BaseModel):
    """
    Parameter schema for action system.set_volume.
    """
    # Parameter attribute validation constraint field mapping for incoming 'level' arguments
    level: int

# Main action routing class definition mapping for parsing 'system.set_volume' structured actions
class SystemSetVolume(BaseModel):
    """
    Main action routing model for system.set_volume.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["set_volume"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemSetVolumeParams

# Declaration of parameter namespace schema class for 'system.update_volume' action constraints
class SystemUpdateVolumeParams(BaseModel):
    """
    Parameter schema for action system.update_volume.
    """
    # Parameter attribute validation constraint field mapping for incoming 'amount' arguments
    amount: int

# Main action routing class definition mapping for parsing 'system.update_volume' structured actions
class SystemUpdateVolume(BaseModel):
    """
    Main action routing model for system.update_volume.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["update_volume"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemUpdateVolumeParams

# Declaration of parameter namespace schema class for 'system.set_brightness' action constraints
class SystemSetBrightnessParams(BaseModel):
    """
    Parameter schema for action system.set_brightness.
    """
    # Parameter attribute validation constraint field mapping for incoming 'level' arguments
    level: int

# Main action routing class definition mapping for parsing 'system.set_brightness' structured actions
class SystemSetBrightness(BaseModel):
    """
    Main action routing model for system.set_brightness.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["set_brightness"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemSetBrightnessParams

# Declaration of parameter namespace schema class for 'system.update_brightness' action constraints
class SystemUpdateBrightnessParams(BaseModel):
    """
    Parameter schema for action system.update_brightness.
    """
    # Parameter attribute validation constraint field mapping for incoming 'amount' arguments
    amount: int

# Main action routing class definition mapping for parsing 'system.update_brightness' structured actions
class SystemUpdateBrightness(BaseModel):
    """
    Main action routing model for system.update_brightness.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["update_brightness"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemUpdateBrightnessParams

# Main action routing class definition mapping for parsing 'system.read_volume' structured actions
class SystemReadVolume(BaseModel):
    """
    Main action routing model for system.read_volume.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["read_volume"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'system.hide_apps' action constraints
class SystemHideAppsParams(BaseModel):
    """
    Parameter schema for action system.hide_apps.
    """
    # Parameter attribute validation constraint field mapping for incoming 'target' arguments
    target: Literal["all", "others", "current"]

# Main action routing class definition mapping for parsing 'system.hide_apps' structured actions
class SystemHideApps(BaseModel):
    """
    Main action routing model for system.hide_apps.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["hide_apps"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemHideAppsParams

# Main action routing class definition mapping for parsing 'system.eject_disks' structured actions
class SystemEjectDisks(BaseModel):
    """
    Main action routing model for system.eject_disks.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["eject_disks"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'system.toggle_dark_mode' action constraints
class SystemToggleDarkModeParams(BaseModel):
    """
    Parameter schema for action system.toggle_dark_mode.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["on", "off"]

# Main action routing class definition mapping for parsing 'system.toggle_dark_mode' structured actions
class SystemToggleDarkMode(BaseModel):
    """
    Main action routing model for system.toggle_dark_mode.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["toggle_dark_mode"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemToggleDarkModeParams

# Main action routing class definition mapping for parsing 'system.sleep' structured actions
class SystemSleep(BaseModel):
    """
    Main action routing model for system.sleep.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["sleep"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'system.shutdown' structured actions
class SystemShutDown(BaseModel):
    """
    Main action routing model for system.shutdown.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["shutdown"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'system.restart' structured actions
class SystemRestart(BaseModel):
    """
    Main action routing model for system.restart.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["restart"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'system.lock_screen' structured actions
class SystemLockScreen(BaseModel):
    """
    Main action routing model for system.lock_screen.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["lock_screen"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams


class SystemToggleWifiParams(BaseModel):
    state: Literal["on", "off"]

class SystemToggleWifi(BaseModel):
    """
    Main action routing class definition mapping for parsing 'system.toggle_wifi' structured actions
    """
    # Fixed literal string identifying the target application module category
    app: Literal["system"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["toggle_wifi"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SystemToggleWifiParams


# ==========================================
# SAFARI ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'safari.open' structured actions
class SafariOpen(BaseModel):
    """
    Main action routing model for safari.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'safari.close' action constraints
class SafariCloseParams(BaseModel):
    """
    Parameter schema for action safari.close.
    """
    # Parameter attribute validation constraint field mapping for incoming 'target' arguments
    target: Literal["all", "current"]

# Main action routing class definition mapping for parsing 'safari.close' structured actions
class SafariClose(BaseModel):
    """
    Main action routing model for safari.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SafariCloseParams

# Declaration of parameter namespace schema class for 'safari.new_tab' action constraints
class SafariNewTabParams(BaseModel):
    """
    Parameter schema for action safari.new_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'url' arguments
    url: Optional[str] = None

# Main action routing class definition mapping for parsing 'safari.new_tab' structured actions
class SafariNewTab(BaseModel):
    """
    Main action routing model for safari.new_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["new_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SafariNewTabParams

# Declaration of parameter namespace schema class for 'safari.close_tab' action constraints
class SafariCloseTabParams(BaseModel):
    """
    Parameter schema for action safari.close_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'target' arguments
    target: Literal["all", "current"]

# Main action routing class definition mapping for parsing 'safari.close_tab' structured actions
class SafariCloseTab(BaseModel):
    """
    Main action routing model for safari.close_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SafariCloseTabParams

# Main action routing class definition mapping for parsing 'safari.get_active_tab_url' structured actions
class SafariGetActiveTabURL(BaseModel):
    """
    Main action routing model for safari.get_active_tab_url.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_active_tab_url"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'safari.get_active_tab_title' structured actions
class SafariGetActiveTabTitle(BaseModel):
    """
    Main action routing model for safari.get_active_tab_title.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_active_tab_title"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'safari.navigate_tab' action constraints
class SafariNavigateTabParams(BaseModel):
    """
    Parameter schema for action safari.navigate_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'direction' arguments
    direction: Literal["back", "forward"]

# Main action routing class definition mapping for parsing 'safari.navigate_tab' structured actions
class SafariNavigateTab(BaseModel):
    """
    Main action routing model for safari.navigate_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["navigate_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SafariNavigateTabParams

# Main action routing class definition mapping for parsing 'safari.refresh' structured actions
class SafariRefreshPage(BaseModel):
    """
    Main action routing model for safari.refresh.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["safari"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["refresh"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams


# ==========================================
# GOOGLE CHROME ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'google chrome.open' structured actions
class ChromeOpen(BaseModel):
    """
    Main action routing model for google chrome.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'google chrome.close' action constraints
class ChromeCloseParams(BaseModel):
    """
    Parameter schema for action google chrome.close.
    """
    # Parameter attribute validation constraint field mapping for incoming 'target' arguments
    target: Literal["all", "current"]

# Main action routing class definition mapping for parsing 'google chrome.close' structured actions
class ChromeClose(BaseModel):
    """
    Main action routing model for google chrome.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: ChromeCloseParams

# Declaration of parameter namespace schema class for 'google chrome.new_tab' action constraints
class ChromeNewTabParams(BaseModel):
    """
    Parameter schema for action google chrome.new_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'url' arguments
    url: Optional[str] = None

# Main action routing class definition mapping for parsing 'google chrome.new_tab' structured actions
class ChromeNewTab(BaseModel):
    """
    Main action routing model for google chrome.new_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["new_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: ChromeNewTabParams

# Declaration of parameter namespace schema class for 'google chrome.close_tab' action constraints
class ChromeCloseTabParams(BaseModel):
    """
    Parameter schema for action google chrome.close_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'target' arguments
    target: Literal["all", "current"]

# Main action routing class definition mapping for parsing 'google chrome.close_tab' structured actions
class ChromeCloseTab(BaseModel):
    """
    Main action routing model for google chrome.close_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: ChromeCloseTabParams

# Main action routing class definition mapping for parsing 'google chrome.get_active_tab_url' structured actions
class ChromeGetActiveTabURL(BaseModel):
    """
    Main action routing model for google chrome.get_active_tab_url.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_active_tab_url"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'google chrome.navigate_tab' action constraints
class ChromeNavigateTabParams(BaseModel):
    """
    Parameter schema for action google chrome.navigate_tab.
    """
    # Parameter attribute validation constraint field mapping for incoming 'direction' arguments
    direction: Literal["back", "forward"]

# Main action routing class definition mapping for parsing 'google chrome.navigate_tab' structured actions
class ChromeNavigateTab(BaseModel):
    """
    Main action routing model for google chrome.navigate_tab.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["navigate_tab"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: ChromeNavigateTabParams

# Main action routing class definition mapping for parsing 'google chrome.refresh' structured actions
class ChromeRefreshPage(BaseModel):
    """
    Main action routing model for google chrome.refresh.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["refresh"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

class ChromeOpenNewWindowParams(BaseModel):
    """
    Parameter schema for action google chrome.open_new_window.
    """
    # Parameter attribute validation constraint field mapping for incoming 'url' arguments
    url: Optional[str] = None

# Main action routing class definition mapping for parsing 'google chrome.open_new_window' structured actions
class ChromeOpenNewWindow(BaseModel):
    """
    Main action routing model for google chrome.open_new_window.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["google chrome"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open_new_window"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: ChromeOpenNewWindowParams


# ==========================================
# APPLE-MUSIC ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'apple-music.open' structured actions
class AppleMusicOpen(BaseModel):
    """
    Main action routing model for apple-music.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'apple-music.close' structured actions
class AppleMusicClose(BaseModel):
    """
    Main action routing model for apple-music.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'apple-music.change_track' action constraints
class AppleMusicTrackChangeParams(BaseModel):
    """
    Parameter schema for action apple-music.change_track.
    """
    # Parameter attribute validation constraint field mapping for incoming 'direction' arguments
    direction: Literal["next", "previous"]

# Main action routing class definition mapping for parsing 'apple-music.change_track' structured actions
class AppleMusicTrackChange(BaseModel):
    """
    Main action routing model for apple-music.change_track.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["change_track"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: AppleMusicTrackChangeParams

# Declaration of parameter namespace schema class for 'apple-music.toggle_playback' action constraints
class AppleMusicTogglePlaybackParams(BaseModel):
    """
    Parameter schema for action apple-music.toggle_playback.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["play", "pause"]

# Main action routing class definition mapping for parsing 'apple-music.toggle_playback' structured actions
class AppleMusicTogglePlayback(BaseModel):
    """
    Main action routing model for apple-music.toggle_playback.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["toggle_playback"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: AppleMusicTogglePlaybackParams

# Main action routing class definition mapping for parsing 'apple-music.get_playing_song_details' structured actions
class AppleMusicGetPlayingSongDetails(BaseModel):
    """
    Main action routing model for apple-music.get_playing_song_details.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_playing_song_details"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'apple-music.add_to_favorites' structured actions
class AppleMusicAddToFavorites(BaseModel):
    """
    Main action routing model for apple-music.add_to_favorites.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["add_to_favorites"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'apple-music.remove_from_favorites' structured actions
class AppleMusicRemoveFromFavorites(BaseModel):
    """
    Main action routing model for apple-music.remove_from_favorites.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["remove_from_favorites"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'apple-music.shuffle' action constraints
class AppleMusicShuffleParams(BaseModel):
    """
    Parameter schema for action apple-music.shuffle.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["on", "off"]

# Main action routing class definition mapping for parsing 'apple-music.shuffle' structured actions
class AppleMusicShuffle(BaseModel):
    """
    Main action routing model for apple-music.shuffle.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["shuffle"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: AppleMusicShuffleParams

# Declaration of parameter namespace schema class for 'apple-music.repeat' action constraints
class AppleMusicRepeatParams(BaseModel):
    """
    Parameter schema for action apple-music.repeat.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["one", "queue", "none"]

# Main action routing class definition mapping for parsing 'apple-music.repeat' structured actions
class AppleMusicRepeat(BaseModel):
    """
    Main action routing model for apple-music.repeat.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["apple-music"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["repeat"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: AppleMusicRepeatParams


# ==========================================
# SPOTIFY ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'spotify.open' structured actions
class SpotifyOpen(BaseModel):
    """
    Main action routing model for spotify.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'spotify.close' structured actions
class SpotifyClose(BaseModel):
    """
    Main action routing model for spotify.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'spotify.change_track' action constraints
class SpotifyTrackChangeParams(BaseModel):
    """
    Parameter schema for action spotify.change_track.
    """
    # Parameter attribute validation constraint field mapping for incoming 'direction' arguments
    direction: Literal["next", "previous"]

# Main action routing class definition mapping for parsing 'spotify.change_track' structured actions
class SpotifyTrackChange(BaseModel):
    """
    Main action routing model for spotify.change_track.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["change_track"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SpotifyTrackChangeParams

# Declaration of parameter namespace schema class for 'spotify.toggle_playback' action constraints
class SpotifyTogglePlaybackParams(BaseModel):
    """
    Parameter schema for action spotify.toggle_playback.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["play", "pause"]

# Main action routing class definition mapping for parsing 'spotify.toggle_playback' structured actions
class SpotifyTogglePlayback(BaseModel):
    """
    Main action routing model for spotify.toggle_playback.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["toggle_playback"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SpotifyTogglePlaybackParams

# Main action routing class definition mapping for parsing 'spotify.get_playing_song_details' structured actions
class SpotifyGetPlayingSongDetails(BaseModel):
    """
    Main action routing model for spotify.get_playing_song_details.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_playing_song_details"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'spotify.shuffle' action constraints
class SpotifyShuffleParams(BaseModel):
    """
    Parameter schema for action spotify.shuffle.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["on", "off"]

# Main action routing class definition mapping for parsing 'spotify.shuffle' structured actions
class SpotifyShuffle(BaseModel):
    """
    Main action routing model for spotify.shuffle.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["shuffle"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SpotifyShuffleParams

# Declaration of parameter namespace schema class for 'spotify.repeat' action constraints
class SpotifyRepeatParams(BaseModel):
    """
    Parameter schema for action spotify.repeat.
    """
    # Parameter attribute validation constraint field mapping for incoming 'state' arguments
    state: Literal["one", "queue", "none"]

# Main action routing class definition mapping for parsing 'spotify.repeat' structured actions
class SpotifyRepeat(BaseModel):
    """
    Main action routing model for spotify.repeat.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["repeat"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SpotifyRepeatParams

# Declaration of parameter namespace schema class for 'spotify.search_and_play' action constraints
class SpotifySearchAndPlayParams(BaseModel):
    """
    Parameter schema for action spotify.search_and_play.
    """
    # Parameter attribute validation constraint field mapping for incoming 'query' arguments
    query: str
    # Parameter attribute validation constraint field mapping for incoming 'scope' arguments
    scope: Literal["song", "album", "artist", "playlist", "any"]

# Main action routing class definition mapping for parsing 'spotify.search_and_play' structured actions
class SpotifySearchAndPlay(BaseModel):
    """
    Main action routing model for spotify.search_and_play.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["spotify"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["search_and_play"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: SpotifySearchAndPlayParams


# ==========================================
# NOTES ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'notes.open' structured actions
class NotesOpen(BaseModel):
    """
    Main action routing model for notes.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'notes.close' structured actions
class NotesClose(BaseModel):
    """
    Main action routing model for notes.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'notes.get_notes' structured actions
class NotesGetNotes(BaseModel):
    """
    Main action routing model for notes.get_notes.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_notes"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'notes.create_note' action constraints
class NotesCreateNoteParams(BaseModel):
    """
    Parameter schema for action notes.create_note.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'content' arguments
    content: str

# Main action routing class definition mapping for parsing 'notes.create_note' structured actions
class NotesCreateNote(BaseModel):
    """
    Main action routing model for notes.create_note.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["create_note"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: NotesCreateNoteParams

# Declaration of parameter namespace schema class for 'notes.get_note_content' action constraints
class NotesGetNoteContentParams(BaseModel):
    """
    Parameter schema for action notes.get_note_content.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str

# Main action routing class definition mapping for parsing 'notes.get_note_content' structured actions
class NotesGetNoteContent(BaseModel):
    """
    Main action routing model for notes.get_note_content.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_note_content"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: NotesGetNoteContentParams

# Declaration of parameter namespace schema class for 'notes.update_note' action constraints
class NotesAddToNoteParams(BaseModel):
    """
    Parameter schema for action notes.update_note.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'content' arguments
    content: str

# Main action routing class definition mapping for parsing 'notes.update_note' structured actions
class NotesAddToNote(BaseModel):
    """
    Main action routing model for notes.update_note.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["notes"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["update_note"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: NotesAddToNoteParams


# ==========================================
# CALENDAR ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'calendar.open' structured actions
class CalendarOpen(BaseModel):
    """
    Main action routing model for calendar.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'calendar.close' structured actions
class CalendarClose(BaseModel):
    """
    Main action routing model for calendar.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'calendar.get_events' action constraints
class CalendarGetEventsParams(BaseModel):
    """
    Parameter schema for action calendar.get_events.
    """
    # Parameter attribute validation constraint field mapping for incoming 'date' arguments
    date: str

# Main action routing class definition mapping for parsing 'calendar.get_events' structured actions
class CalendarGetEvents(BaseModel):
    """
    Main action routing model for calendar.get_events.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_events"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: CalendarGetEventsParams

# Declaration of parameter namespace schema class for 'calendar.create_event' action constraints
class CalendarCreateEventParams(BaseModel):
    """
    Parameter schema for action calendar.create_event.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'date' arguments
    date: str
    # Parameter attribute validation constraint field mapping for incoming 'time' arguments
    time: str
    # Parameter attribute validation constraint field mapping for incoming 'duration_in_minutes' arguments
    duration_in_minutes: int
    # Parameter attribute validation constraint field mapping for incoming 'location' arguments
    location: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'description' arguments
    description: Optional[str] = None

# Main action routing class definition mapping for parsing 'calendar.create_event' structured actions
class CalendarCreateEvent(BaseModel):
    """
    Main action routing model for calendar.create_event.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["create_event"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: CalendarCreateEventParams

# Declaration of parameter namespace schema class for 'calendar.update_event' action constraints
class CalendarUpdateEventParams(BaseModel):
    """
    Parameter schema for action calendar.update_event.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'date' arguments
    date: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'time' arguments
    time: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'duration' arguments
    duration: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'location' arguments
    location: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'description' arguments
    description: Optional[str] = None

# Main action routing class definition mapping for parsing 'calendar.update_event' structured actions
class CalendarUpdateEvent(BaseModel):
    """
    Main action routing model for calendar.update_event.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["update_event"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: CalendarUpdateEventParams

# Declaration of parameter namespace schema class for 'calendar.read_event' action constraints
class CalendarReadEventParams(BaseModel):
    """
    Parameter schema for action calendar.read_event.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'date' arguments
    date: Optional[str] = None

# Main action routing class definition mapping for parsing 'calendar.read_event' structured actions
class CalendarReadEvent(BaseModel):
    """
    Main action routing model for calendar.read_event.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["calendar"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["read_event"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: CalendarReadEventParams


# ==========================================
# REMINDERS ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'reminders.open' structured actions
class RemindersOpen(BaseModel):
    """
    Main action routing model for reminders.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'reminders.close' structured actions
class RemindersClose(BaseModel):
    """
    Main action routing model for reminders.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'reminders.get_reminders' structured actions
class RemindersGetReminders(BaseModel):
    """
    Main action routing model for reminders.get_reminders.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["get_reminders"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'reminders.create_reminder' action constraints
class RemindersCreateReminderParams(BaseModel):
    """
    Parameter schema for action reminders.create_reminder.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'date' arguments
    date: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'time' arguments
    time: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'notes' arguments
    notes: Optional[str] = None

# Main action routing class definition mapping for parsing 'reminders.create_reminder' structured actions
class RemindersCreateReminder(BaseModel):
    """
    Main action routing model for reminders.create_reminder.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["create_reminder"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: RemindersCreateReminderParams

# Declaration of parameter namespace schema class for 'reminders.update_reminder' action constraints
class RemindersUpdateReminderParams(BaseModel):
    """
    Parameter schema for action reminders.update_reminder.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str
    # Parameter attribute validation constraint field mapping for incoming 'new_title' arguments
    new_title: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'new_date' arguments
    new_date: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'new_time' arguments
    new_time: Optional[str] = None
    # Parameter attribute validation constraint field mapping for incoming 'new_notes' arguments
    new_notes: Optional[str] = None

# Main action routing class definition mapping for parsing 'reminders.update_reminder' structured actions
class RemindersUpdateReminder(BaseModel):
    """
    Main action routing model for reminders.update_reminder.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["update_reminder"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: RemindersUpdateReminderParams

# Declaration of parameter namespace schema class for 'reminders.delete_reminder' action constraints
class RemindersDeleteReminderParams(BaseModel):
    """
    Parameter schema for action reminders.delete_reminder.
    """
    # Parameter attribute validation constraint field mapping for incoming 'title' arguments
    title: str

# Main action routing class definition mapping for parsing 'reminders.delete_reminder' structured actions
class RemindersDeleteReminder(BaseModel):
    """
    Main action routing model for reminders.delete_reminder.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["reminders"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["delete_reminder"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: RemindersDeleteReminderParams


# ==========================================
# TEXTEDIT ACTIONS
# ==========================================
# Main action routing class definition mapping for parsing 'textedit.open' structured actions
class TextEditOpen(BaseModel):
    """
    Main action routing model for textedit.open.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["textedit"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'textedit.close' structured actions
class TextEditClose(BaseModel):
    """
    Main action routing model for textedit.close.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["textedit"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["close"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Main action routing class definition mapping for parsing 'textedit.new_document' structured actions
class TextEditNewDocument(BaseModel):
    """
    Main action routing model for textedit.new_document.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["textedit"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["new_document"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

# Declaration of parameter namespace schema class for 'textedit.open_document' action constraints
class TextEditOpenDocumentParams(BaseModel):
    """
    Parameter schema for action textedit.open_document.
    """
    # Parameter attribute validation constraint field mapping for incoming 'path' arguments
    path: str

# Main action routing class definition mapping for parsing 'textedit.open_document' structured actions
class TextEditOpenDocument(BaseModel):
    """
    Main action routing model for textedit.open_document.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["textedit"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["open_document"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: TextEditOpenDocumentParams


# ==========================================
# ROUTER ACTIONS
# ==========================================
# Declaration of parameter namespace schema class for 'router.llm-agent' action constraints
class RouterLlmAgentParams(BaseModel):
    """
    Parameter schema for action router.llm-agent.
    """
    # Parameter attribute validation constraint field mapping for incoming 'task' arguments
    task: str

# Main action routing class definition mapping for parsing 'router.llm-agent' structured actions
class RouterLlmAgent(BaseModel):
    """
    Main action routing model for router.llm-agent.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["router"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["llm-agent"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: RouterLlmAgentParams

# Main action routing class definition mapping for parsing 'router.do-nothing' structured actions
class RouterDoNothing(BaseModel):
    """
    Main action routing model for router.do-nothing.
    """
    # Fixed literal string identifying the target application module category
    app: Literal["router"]
    # Fixed literal string identifying the specific routing execution endpoint verb
    action: Literal["do-nothing"]
    # Nested namespace block to validate parameter inputs mapped to their respective formats
    params: EmptyParams

