"""
================================================================================
Lucky Core Engine - Translation and Execution Bridge
================================================================================
This module serves as the primary translation layer (bridge) between the structured
JSON action schemas generated by the language model (defined in src/actions.py)
and executable macOS terminal instructions (specifically AppleScript via osascript
and native shell commands).

Technical Specifications:
- Dict-based routing: Dynamically associates parsed action categories (app, action)
  with their validation schemas and specific translation procedures.
- Heredoc wrapping: Formats multi-line AppleScript structures inside POSIX-compliant
  shell heredocs (osascript <<'EOF' ... EOF) to guarantee safe execution without
  clumsy string escaping issues for single or double quotes.
- Locale-Independent Date Construction: Manually populates date properties via
  explicit field setters in AppleScript (year, month, day, time) to bypass macOS
  regional settings variation that would break standard string-to-date casting.
- Duration Parser: Implements a regex-based token reader to extract time quantities
  from natural language description values, mapping them to numerical minutes.
"""

# Import the regular expressions module to extract digits and time patterns from input parameters
import re
# Import the os module to perform path manipulations such as home directory expansions
import os
# Import standard JSON utilities to parse and load serialized action strings
import json
# Import the datetime package to perform calendar calculations and date parsing operations
from datetime import datetime
# Import the union typing helper to support polymorphic action schemas
from typing import Union

# Import the base actions module containing the Pydantic models for structured actions
from src import actions
# Import the custom background agent module to execute parallel, non-blocking LLM queries on daemon threads.
# This import enables calling start_agent_thread when a router.llm-agent action is received.
from src import agent
# Import the custom audio module to record or play back sound clips/alerts.
# This enables playing confirmation or completion sounds during action execution.
from src import audio

def parse_duration_to_minutes(duration_str: str) -> int:
    """
    Parses a duration description string (e.g. '30 minutes', '1.5 hours')
    and returns its integer equivalent in total minutes.
    
    Technical Details:
    - Normalizes strings to lowercase and runs regular expression pattern matching.
    - Searches for numbers and identifies unit markers like 'hour', 'hr', 'h' or 'minute', 'min', 'm'.
    - If hours are detected, it multiplies the numerical component by 60.
    """
    # Verify that the input duration string is valid and not empty
    if not duration_str:
        # Return a standard default duration of 60 minutes if none is provided
        return 60
    
    # Convert the string to lowercase and strip outer whitespaces to ensure consistent text matching
    s = duration_str.strip().lower()
    
    # Locate all decimal numbers or integer patterns in the string
    numbers = re.findall(r'\d+(?:\.\d+)?', s)
    # If no numbers were found in the text, return a default duration value
    if not numbers:
        # Standard fallback duration is set to 60 minutes
        return 60
        
    # Convert the first matched numerical group to a floating-point representation
    value = float(numbers[0])
    
    # If the duration string contains hour indicator tokens, scale the value to minutes
    if any(h_token in s for h_token in ["hour", "hr", "h"]):
        # Multiply the value by 60 to convert hours to minutes and return the integer value
        return int(value * 60)
        
    # Default return value is treated as minutes directly, cast to integer
    return int(value)

def format_as_heredoc(applescript_code: str) -> str:
    """
    Wraps raw AppleScript code into a POSIX shell heredoc block calling osascript.
    
    Technical Details:
    - Uses 'osascript <<\'EOF\'' which tells the shell interpreter to pass all lines
      literal-by-literal to the osascript utility without interpreting shell variables or escaping quotes.
    - This is significantly safer than using osascript -e '...' which fails when single quotes exist.
    """
    # Strip unnecessary leading/trailing newlines from the raw script to keep it neat
    cleaned_code = applescript_code.strip()
    # Return the formatted shell heredoc string block using EOF as the delimiter
    return f"osascript <<'EOF'\n{cleaned_code}\nEOF"

# ------------------------------------------------------------------------------
# FINDER TRANSLATORS
# ------------------------------------------------------------------------------

def translate_finder_open(action: actions.FinderOpen) -> str:
    """
    Translates finder.open into an AppleScript command to activate Finder.
    - Uses the 'activate' command to request Finder to bring its windows forward.
    """
    # Return the AppleScript to tell Finder to bring itself to the front
    return format_as_heredoc("tell application \"Finder\" to activate reopen")

def translate_finder_close(action: actions.FinderClose) -> str:
    """
    Translates finder.close into an AppleScript command.
    - Closes either all Finder windows or just the frontmost window.
    """
    # Extract the close scope parameter (either 'all' or 'current')
    scope = action.params.scope
    # If the scope is set to close all windows, tell Finder to close every window
    if scope == "all":
        # Formulate the AppleScript string targeting all windows
        return format_as_heredoc("tell application \"Finder\" to close every window")
    # If the scope is set to close only the active window, close the front window
    else:
        # Formulate the AppleScript string targeting the frontmost window
        return format_as_heredoc("tell application \"Finder\" to close front window")

def translate_finder_empty_trash(action: actions.FinderEmptyTrash) -> str:
    """
    Translates finder.empty_trash into an AppleScript command.
    - Instructs the Finder application to empty the system trash bin.
    """
    # Generate AppleScript to empty system trash
    return format_as_heredoc("tell application \"Finder\" to empty trash")

def translate_finder_get_active_window_path(action: actions.FinderGetActiveWindowPath) -> str:
    """
    Translates finder.get_active_window_path into AppleScript.
    - Retrieves the folder path of the active Finder window.
    - Falls back to the desktop path if no window is open.
    """
    # Construct the AppleScript with conditional checks to avoid errors when no window is active
    script = """
tell application "Finder"
    if exists Finder window 1 then
        get POSIX path of (target of Finder window 1 as alias)
    else
        get POSIX path of (desktop as alias)
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)


# KNOWN ISSUE
# POSIX files are not returned exactly. Will need a multi agent flow here.
def translate_finder_create_folder(action: actions.FinderCreateFolder) -> str:
    """
    Translates finder.create_folder into AppleScript.
    - Expands user paths (e.g. '~') in Python before passing them to the script.
    - Instructs Finder to create a folder at the specified POSIX directory location.
    """
    # Expand home directory symbol '~' to its absolute POSIX path equivalent
    abs_location = os.path.expanduser(action.params.location)
    # Extract the folder name parameter from the schema
    folder_name = action.params.name
    # Construct AppleScript converting the POSIX directory into an alias and making the folder
    script = f"""
tell application "Finder"
    set targetFolder to POSIX file "{abs_location}" as alias
    make new folder at targetFolder with properties {{name:"{folder_name}"}}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# SYSTEM TRANSLATORS
# ------------------------------------------------------------------------------

def translate_system_set_volume(action: actions.SystemSetVolume) -> str:
    """
    Translates system.set_volume into AppleScript.
    - Modifies the hardware volume setting of the host macOS.
    """
    # Retrieve target level from parameters (0-100 range validation done by Pydantic)
    level = action.params.level
    # Formulate AppleScript statement adjusting output volume settings
    return format_as_heredoc(f"set volume output volume {level}")

# KNOWN ISSUE => FIX APPLIED - VERIFY PENDING
# Model gets confused between set and update

def translate_system_update_volume(action: actions.SystemUpdateVolume) -> str:
    """
    Translates system.update_volume into AppleScript.
    - Fetches the current volume level and applies a relative adjustment.
    - Clamps values between 0 and 100 to prevent out-of-range system crashes.
    """
    # Retrieve relative change amount (negative for decrease, positive for increase)
    amount = action.params.amount
    # Create scripting logic to read, adjust, clamp, and write back the output volume settings
    script = f"""
set currentVolume to output volume of (get volume settings)
set newVolume to currentVolume + {amount}
if newVolume < 0 then set newVolume to 0
if newVolume > 100 then set newVolume to 100
set volume output volume newVolume
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_system_set_brightness(action: actions.SystemSetBrightness) -> str:
    """
    Translates system.set_brightness into a shell command.
    - Attempts to use the brew utility 'brightness'.
    - If unavailable, falls back to triggering system keycodes for brightness.
    """
    # Extract target level (0-100) and scale it to a float fraction (0.0 to 1.0)
    level_fraction = action.params.level / 100.0
    # Write a bash command that checks if 'brightness' exists, else uses osascript keypresses
    cmd = f"swift -e 'import DisplayServices; DisplayServicesSetLinearBrightness(0, {level_fraction})'"
    # Return the raw bash script commands directly (no heredoc wrap since it has its own logic)
    return cmd.strip()

def translate_system_update_brightness(action: actions.SystemUpdateBrightness) -> str:
    """
    Translates system.update_brightness into a Swift-based display services command.
    - Reads the current display brightness level from the system display services.
    - Applies a relative offset, scaling the percentage value to a 0.0-1.0 float.
    - Clamps the value to ensure the target brightness is positive and between 0.0 and 1.0 (0-100%).
    - Invokes DisplayServicesSetLinearBrightness to set the final brightness.
    """
    # Extract the relative change offset amount from Pydantic action parameter fields
    amount = action.params.amount
    # Convert the percentage integer offset into a double/float fraction representation
    amount_fraction = amount / 100.0
    
    # Formulate a Swift command line string that imports private framework APIs,
    # queries current screen brightness using GetLinearBrightness, calculates the relative
    # offset adjustment, clamps results to [0.0, 1.0] range, and sets display brightness.
    script = (
        "swift -e 'import DisplayServices; "
        "var current: Float = 0.0; "
        "DisplayServicesGetLinearBrightness(0, &current); "
        f"var newBrightness = current + {amount_fraction}; "
        "if newBrightness < 0.0 { newBrightness = 0.0 }; "
        "if newBrightness > 1.0 { newBrightness = 1.0 }; "
        "DisplayServicesSetLinearBrightness(0, newBrightness)'"
    )
    # Return the clean compiled command string directly for terminal subprocess execution
    return script.strip()


def translate_system_read_volume(action: actions.SystemReadVolume) -> str:
    """
    Translates system.read_volume into AppleScript.
    - Retrieves the current output volume from system settings.
    """
    # Formulate AppleScript query statement
    return format_as_heredoc("output volume of (get volume settings)")

def translate_system_hide_apps(action: actions.SystemHideApps) -> str:
    """
    Translates system.hide_apps into AppleScript.
    - Hides applications based on the 'target' parameter ('all', 'others', 'current').
    """
    # Extract target scope option
    target = action.params.target
    # Handle the 'others' scope by simulating Cmd+Option+H keystroke shortcut
    if target == "others":
        script = """
tell application "System Events"
    keystroke "h" using {command down, option down}
end tell
"""
    # Handle the 'current' active app by simulating standard Cmd+H shortcut
    elif target == "current":
        script = """
tell application "System Events"
    keystroke "h" using {command down}
end tell
"""
    # Handle the 'all' scope by cycling through active visible processes
    else:
        script = """
tell application "System Events"
    set visible of every process whose visible is true to false
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_system_eject_disks(action: actions.SystemEjectDisks) -> str:
    """
    Translates system.eject_disks into AppleScript.
    - Instructs Finder to eject every removable disk volume.
    """
    # Formulate AppleScript to eject volumes
    return format_as_heredoc("tell application \"Finder\" to eject (every disk whose ejectable is true)")

def translate_system_toggle_dark_mode(action: actions.SystemToggleDarkMode) -> str:
    """
    Translates system.toggle_dark_mode into AppleScript.
    - Adjusts macOS appearance preferences to enable or disable dark mode.
    """
    # Convert the state parameter string into a boolean flag
    dark_mode_bool = "true" if action.params.state == "on" else "false"
    # Create the script altering the preferences object
    script = f"""
tell application "System Events"
    tell appearance preferences
        set dark mode to {dark_mode_bool}
    end tell
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_system_sleep(action: actions.SystemSleep) -> str:
    """
    Translates system.sleep into AppleScript.
    - Puts the host macOS machine into low-power sleep mode.
    """
    # Formulate AppleScript instruction to Finder to sleep the system
    return format_as_heredoc("tell application \"Finder\" to sleep")

def translate_system_shutdown(action: actions.SystemShutDown) -> str:
    """
    Translates system.shutdown into AppleScript.
    - Power off the system via Finder.
    """
    # Formulate AppleScript instruction to Finder to turn off the computer
    return format_as_heredoc("tell application \"Finder\" to shut down")

def translate_system_restart(action: actions.SystemRestart) -> str:
    """
    Translates system.restart into AppleScript.
    - Reboots the machine via Finder.
    """
    # Formulate AppleScript instruction to Finder to restart the computer
    return format_as_heredoc("tell application \"Finder\" to restart")

def translate_system_lock_screen(action: actions.SystemLockScreen) -> str:
    """
    Translates system.lock_screen into AppleScript/Shell.
    - Simulates the standard macOS screen locking shortcut (Cmd+Ctrl+Q).
    """
    # Create keycode combination sequence for System Events
    script = """
tell application "System Events" to keystroke "q" using {control down, command down}
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_system_toggle_wifi(action: actions.SystemToggleWifi) -> str:
    """
    Translates system.toggle_wifi into a shell command.
    - Dynamically queries the macOS hardware network ports to locate the Wi-Fi device name.
    - Enables or disables wireless interface power based on the parameter state.

    Technical Details:
    - Resolves target state parameter ("on" or "off") from SystemToggleWifiParams.
    - Constructs zsh/bash command scripting to parse output of 'networksetup -listallhardwareports'.
    - Feeds device identifier enX into 'networksetup -setairportpower' utility command.
    """
    # Extract the target wifi interface power state parameter from the validated Pydantic parameters block.
    # This attribute holds the literal string value ('on' or 'off') indicating the user's intent.
    state = action.params.state

    # Construct the shell script command sequence to toggle the hardware Wi-Fi power states.
    # We write a pipeline shell command:
    # 1. 'networksetup -listallhardwareports' query lists all hardware interfaces and port names.
    # 2. 'awk' command matches the keyword 'Wi-Fi', moves down one line to access the 'Device: enX' row, and parses the interface name.
    # 3. We store that interface name in a shell variable named 'device'.
    # 4. We evaluate if the device variable length is non-zero, then execute networksetup with -setairportpower option to toggle power state.
    cmd = (
        f"device=$(networksetup -listallhardwareports | awk '/Wi-Fi/{{getline; print $2}}'); "
        f"if [ -n \"$device\" ]; then "
        f"networksetup -setairportpower \"$device\" {state}; "
        f"fi"
    )

    audio.play_audio("audio/done.mp3", wait=False)

    # Return the formatted shell command string to be executed inside a subprocess shell shell environment.
    # We strip trailing/leading spaces to guarantee a clean string payload structure.
    return cmd.strip()

# ------------------------------------------------------------------------------
# SAFARI TRANSLATORS
# ------------------------------------------------------------------------------

def translate_safari_open(action: actions.SafariOpen) -> str:
    """
    Translates safari.open into AppleScript.
    - Opens and activates Safari.
    """
    # Formulate activation AppleScript command
    return format_as_heredoc("tell application \"Safari\" to activate reopen")

def translate_safari_close(action: actions.SafariClose) -> str:
    """
    Translates safari.close into AppleScript.
    - Quits Safari ('all') or closes the front window ('current').
    """
    # Extract the window target parameter
    target = action.params.target
    # Handle the global exit scope
    if target == "all":
        script = "tell application \"Safari\" to quit"
    # Handle closing the active frontmost window
    else:
        script = """
tell application "Safari"
    if (count of windows) > 0 then
        close window 1
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_new_tab(action: actions.SafariNewTab) -> str:
    """
    Translates safari.new_tab into AppleScript.
    - Creates a new tab. If a URL is provided, navigates to it.
    - Ensures a window is active before making the tab.
    """
    # Retrieve the URL argument, substituting empty string if None
    url = action.params.url or ""
    # Define conditional AppleScript blocks depending on URL availability
    if url:
        tab_action = f"set current tab to (make new tab with properties {{URL:\"{url}\"}})"
    else:
        tab_action = "set current tab to (make new tab)"
        
    # Build complete Safari setup scripting block
    script = f"""
tell application "Safari"
    activate
    if (count of windows) is 0 then
        make new document
    end if
    tell window 1
        {tab_action}
    end tell
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_close_tab(action: actions.SafariCloseTab) -> str:
    """
    Translates safari.close_tab into AppleScript.
    - Closes either the active tab or all tabs in the front window.
    """
    # Extract target scope
    target = action.params.target
    # If target is 'current', close the active tab of the front window
    if target == "current":
        script = """
tell application "Safari"
    if (count of windows) > 0 then
        tell window 1 to close current tab
    end if
end tell
"""
    # If target is 'all', close every tab of the front window
    else:
        script = """
tell application "Safari"
    if (count of windows) > 0 then
        tell window 1 to close every tab
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_get_active_tab_url(action: actions.SafariGetActiveTabURL) -> str:
    """
    Translates safari.get_active_tab_url into AppleScript.
    - Retrieves the URL string of the active tab.
    """
    # Create query script targeting Safari window 1
    script = """
tell application "Safari"
    if (count of windows) > 0 then
        get URL of current tab of window 1
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_get_active_tab_title(action: actions.SafariGetActiveTabTitle) -> str:
    """
    Translates safari.get_active_tab_title into AppleScript.
    - Retrieves the page title string of the active tab.
    """
    # Create query script targeting Safari window 1
    script = """
tell application "Safari"
    if (count of windows) > 0 then
        get name of current tab of window 1
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_navigate_tab(action: actions.SafariNavigateTab) -> str:
    """
    Translates safari.navigate_tab into AppleScript.
    - Moves back or forward in history for the active tab.
    """
    # Extract direction (either 'back' or 'forward')
    direction = action.params.direction
    # Map direction to standard AppleScript navigation keywords
    verb = "[" if direction == "back" else "]"
    # Build the navigation script block
    script = f"""
tell application "Safari"
    if (count of windows) > 0 then
        activate
        tell application "System Events"
            keystroke "{verb}" using command down
        end tell
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_safari_refresh_page(action: actions.SafariRefreshPage) -> str:
    """
    Translates safari.refresh into AppleScript.
    - Reloads the current webpage by re-setting its URL to its current value.
    """
    # Create refresh AppleScript
    script = """
tell application "Safari"
    if (count of windows) > 0 then
        tell window 1
            set URL of current tab to (get URL of current tab)
        end tell
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# GOOGLE CHROME TRANSLATORS
# ------------------------------------------------------------------------------

def translate_chrome_open(action: actions.ChromeOpen) -> str:
    """
    Translates google chrome.open into AppleScript.
    - Activates Google Chrome.
    """
    # Formulate activation script
    return format_as_heredoc("tell application \"Google Chrome\" to activate")

# KNOWN ISSUE
# Triggers even when AI misheard something like "close 45"
def translate_chrome_close(action: actions.ChromeClose) -> str:
    """
    Translates google chrome.close into AppleScript.
    - Quits Chrome ('all') or closes the front window ('current').
    """
    # Extract target scope
    target = action.params.target
    # Handle global app exit
    if target == "all":
        script = "tell application \"Google Chrome\" to quit"
    # Handle frontmost window close
    else:
        script = """
tell application "Google Chrome"
    if (count of windows) > 0 then
        close window 1
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_chrome_new_tab(action: actions.ChromeNewTab) -> str:
    """
    Translates google chrome.new_tab into AppleScript.
    - Opens a new tab, loading the URL if provided.
    """
    # Extract the optional URL parameter
    url = action.params.url or ""
    # Format the tab creation command
    if url:
        tab_action = f"make new tab with properties {{URL:\"{url}\"}}"
    else:
        tab_action = "make new tab"
        
    # Build complete execution script checking for windows
    script = f"""
tell application "Google Chrome"
    activate
    if (count of windows) is 0 then
        make new window
    end if
    tell window 1
        {tab_action}
    end tell
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_chrome_close_tab(action: actions.ChromeCloseTab) -> str:
    """
    Translates google chrome.close_tab into AppleScript.
    - Closes either the active tab or all tabs in the front window.
    """
    # Extract target scope
    target = action.params.target
    # Handle active tab close
    if target == "current":
        script = """
tell application "Google Chrome"
    if (count of windows) > 0 then
        tell window 1 to close active tab
    end if
end tell
"""
    # Handle closing all tabs in the window
    else:
        script = """
tell application "Google Chrome"
    if (count of windows) > 0 then
        tell window 1 to close every tab
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE
# Doesn't open URLs. Only 1 row in dataset to teach this
def translate_chrome_get_active_tab_url(action: actions.ChromeGetActiveTabURL) -> str:
    """
    Translates google chrome.get_active_tab_url into AppleScript.
    - Retrieves the URL of the active tab.
    """
    # Create query script targeting Chrome window 1
    script = """
tell application "Google Chrome"
    if (count of windows) > 0 then
        get URL of active tab of window 1
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_chrome_navigate_tab(action: actions.ChromeNavigateTab) -> str:
    """
    Translates google chrome.navigate_tab into AppleScript.
    - Since Chrome lacks native go back/forward AppleScript API hooks,
      we bring Chrome forward and trigger standard shortcuts (Cmd+[ or Cmd+]).
    """
    # Extract target history direction
    direction = action.params.direction
    # Select keystroke character representing history navigation commands
    char = "[" if direction == "back" else "]"
    # Build the keystroke simulation block
    script = f"""
tell application "Google Chrome" to activate
tell application "System Events"
    keystroke "{char}" using {{command down}}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_chrome_refresh_page(action: actions.ChromeRefreshPage) -> str:
    """
    Translates google chrome.refresh into AppleScript.
    - Triggers the native 'reload' action on Chrome's active tab.
    """
    # Formulate reload scripting block
    script = """
tell application "Google Chrome"
    if (count of windows) > 0 then
        tell window 1 to reload active tab
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)


# KNOWN ISSUE - FIXED YET TO VERIFY
# Should have a URL parameter
def translate_chrome_open_new_window(action: actions.ChromeOpenNewWindow) -> str:
    """
    Translates google chrome.open_new_window into AppleScript.
    - Spawns a brand new window instance in Chrome.
    - If a URL is provided, navigates the active tab of that new window to the URL.
    
    Technical Details:
    - Extracts the url param from ChromeOpenNewWindowParams.
    - Conditionally formats the AppleScript to target the active tab of the new window object.
    - Wraps the script in a heredoc wrapper for safe shell execution.
    """
    # Access the params dictionary/object via the action object and extract the URL attribute, defaulting to an empty string if it is None.
    # This is necessary because Pydantic models might return None if the optional field was not populated.
    url = action.params.url or ""

    # Evaluate the logical truthiness of the URL string variable to determine whether to perform page navigation.
    # We branch execution to choose between opening a new window with a blank page vs opening one with a specific website loaded.
    if url:
        # Define the multi-line AppleScript string block using Python f-string formatting to interpolate the target URL safely.
        # AppleScript details:
        # - 'make new window' creates a new window container. In Chrome, this object inherently contains one tab (the active/default tab).
        # - Storing the object in a reference variable ('newWindow') allows us to command it without relying on window indexing.
        # - 'set URL of active tab of newWindow to "{url}"' dynamically updates the active tab's location property to our desired URL string.
        # - 'activate' commands the window manager to bring Chrome and this newly opened window into focus.
        script = f"""
tell application "Google Chrome"
    set newWindow to make new window
    set URL of active tab of newWindow to "{url}"
    activate
end tell
"""
    # Execute this alternative block of instructions when the target URL parameter is absent or empty.
    # This branch is required to maintain the original default behavior of launching a blank new window without loading any webpage.
    else:
        # Define the standard multi-line AppleScript string block targeting Google Chrome.
        # It sends a make command to instantiate a window, followed by an activate call to raise the window in macOS window manager.
        script = """
tell application "Google Chrome"
    make new window
    activate
end tell
"""

    # Call the format_as_heredoc utility function to package the formatted AppleScript script inside a shell heredoc block.
    # This encapsulation wraps the commands in an osascript heredoc structure for safe shell execution.
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# APPLE MUSIC TRANSLATORS
# ------------------------------------------------------------------------------

def translate_apple_music_open(action: actions.AppleMusicOpen) -> str:
    """
    Translates apple-music.open into AppleScript.
    - Brings the Music app into focus.
    """
    # Formulate activation script
    return format_as_heredoc("tell application \"Music\" to activate reopen")

def translate_apple_music_close(action: actions.AppleMusicClose) -> str:
    """
    Translates apple-music.close into AppleScript.
    - Shuts down the Music app.
    """
    # Formulate exit script
    return format_as_heredoc("tell application \"Music\" to quit")

def translate_apple_music_change_track(action: actions.AppleMusicTrackChange) -> str:
    """
    Translates apple-music.change_track into AppleScript.
    - Moves to the next or previous track in the queue.
    """
    # Extract target change direction
    direction = action.params.direction
    # Map the direction string to Music app command keywords
    verb = "next track" if direction == "next" else "previous track"
    # Formulate track control script
    return format_as_heredoc(f"tell application \"Music\" to {verb}")


# KNOWN ISSUE - FIXED IN DATA. YET TO VERIFY
# Goes to Spotify instead of Apple Music
def translate_apple_music_toggle_playback(action: actions.AppleMusicTogglePlayback) -> str:
    """
    Translates apple-music.toggle_playback into AppleScript.
    - Starts or pauses track playback.
    """
    # Extract the requested playback state
    state = action.params.state
    # Formulate corresponding play/pause AppleScript command
    return format_as_heredoc(f"tell application \"Music\" to {state}")

def translate_apple_music_get_playing_song_details(action: actions.AppleMusicGetPlayingSongDetails) -> str:
    """
    Translates apple-music.get_playing_song_details into AppleScript.
    - Retrieves details of the currently playing track.
    """
    # Construct script to query metadata properties of the active track
    script = """
tell application "Music"
    if player state is playing then
        set songName to name of current track
        set artistName to artist of current track
        set albumName to album of current track
        return songName & " - " & artistName & " (" & albumName & ")"
    else
        return "No song playing"
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_apple_music_add_to_favorites(action: actions.AppleMusicAddToFavorites) -> str:
    """
    Translates apple-music.add_to_favorites into AppleScript.
    - Attempts to mark the active track as Loved or Favorited (Sonoma+).
    - Uses try-blocks to support different macOS versions.
    """
    # Build version-safe properties updates script
    script = """
tell application "Music"
    if exists current track then
        try
            set loved of current track to true
        on error
            try
                set favorited of current track to true
            end try
        end try
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_apple_music_remove_from_favorites(action: actions.AppleMusicRemoveFromFavorites) -> str:
    """
    Translates apple-music.remove_from_favorites into AppleScript.
    - Clears the Loved/Favorited status from the active track.
    """
    # Build version-safe property clearing script
    script = """
tell application "Music"
    if exists current track then
        try
            set loved of current track to false
        on error
            try
                set favorited of current track to false
            end try
        end try
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_apple_music_shuffle(action: actions.AppleMusicShuffle) -> str:
    """
    Translates apple-music.shuffle into AppleScript.
    - Enables or disables track shuffling.
    """
    # Map on/off state parameter to boolean string
    val = "true" if action.params.state == "on" else "false"
    # Construct script altering the shuffle property
    script = f"""
tell application "Music"
    set shuffle enabled to {val}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_apple_music_repeat(action: actions.AppleMusicRepeat) -> str:
    """
    Translates apple-music.repeat into AppleScript.
    - Maps repeat modes ('one', 'queue', 'none') to Music app properties ('one', 'all', 'off').
    """
    # Extract repeat mode parameter
    state = action.params.state
    # Map parameter names to Music application native repeat enum terms
    enum_val = "one"
    if state == "queue":
        enum_val = "all"
    elif state == "none":
        enum_val = "off"
        
    # Construct property modification script
    script = f"""
tell application "Music"
    set song repeat to {enum_val}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# SPOTIFY TRANSLATORS
# ------------------------------------------------------------------------------

def translate_spotify_open(action: actions.SpotifyOpen) -> str:
    """
    Translates spotify.open into AppleScript.
    - Launches Spotify.
    """
    # Formulate activation command
    return format_as_heredoc("tell application \"Spotify\" to activate reopen")

def translate_spotify_close(action: actions.SpotifyClose) -> str:
    """
    Translates spotify.close into AppleScript.
    - Shuts down the Spotify application process.
    """
    # Formulate quit command
    return format_as_heredoc("tell application \"Spotify\" to quit")

def translate_spotify_change_track(action: actions.SpotifyTrackChange) -> str:
    """
    Translates spotify.change_track into AppleScript.
    - Skips track forward or backward.
    """
    # Extract target direction
    direction = action.params.direction
    # Resolve verb keyword matching direction parameter
    verb = "next track" if direction == "next" else "previous track"
    # Formulate control command
    return format_as_heredoc(f"tell application \"Spotify\" to {verb}")

def translate_spotify_toggle_playback(action: actions.SpotifyTogglePlayback) -> str:
    """
    Translates spotify.toggle_playback into AppleScript.
    - Controls track play/pause states.
    """
    # Extract play or pause command choice
    state = action.params.state
    # Formulate play/pause control instruction
    return format_as_heredoc(f"tell application \"Spotify\" to {state}")

def translate_spotify_get_playing_song_details(action: actions.SpotifyGetPlayingSongDetails) -> str:
    """
    Translates spotify.get_playing_song_details into AppleScript.
    - Retrieves details of the currently playing track.
    """
    # Construct script to query metadata properties of the active track
    script = """
tell application "Spotify"
    if player state is playing then
        set songName to name of current track
        set artistName to artist of current track
        set albumName to album of current track
        return songName & " - " & artistName & " (" & albumName & ")"
    else
        return "No song playing"
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_spotify_shuffle(action: actions.SpotifyShuffle) -> str:
    """
    Translates spotify.shuffle into AppleScript.
    - Enables or disables track shuffling.
    """
    # Map state string to boolean representation
    val = "true" if action.params.state == "on" else "false"
    # Formulate property update script
    script = f"""
tell application "Spotify"
    set shuffling to {val}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE
# Repeat one does not work as intended.
def translate_spotify_repeat(action: actions.SpotifyRepeat) -> str:
    """
    Translates spotify.repeat into AppleScript.
    - Since Spotify's AppleScript library only supports a boolean 'repeating' property,
      any active repeat ('one' or 'queue') turns repeating on.
    """
    # Map repeating choice to a boolean string representation
    val = "false" if action.params.state == "none" else "true"
    # Formulate property update script
    script = f"""
tell application "Spotify"
    set repeating to {val}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE - FIXED YET TO VERIFY
# Keeps going to toggle play/pause instead of here.
def translate_spotify_search_and_play(action: actions.SpotifySearchAndPlay) -> str:
    """
    Translates spotify.search_and_play into AppleScript.
    - Uses the Spotify search URL scheme to direct the application to the query results page.
    """
    # Extract search query text
    query = action.params.query
    scope = action.params.scope if action.params.scope else "song"
    num_of_presses = 5
    

    # Construct script using open location scheme to trigger a search
#     script = f"""
# tell application "Spotify"
#     activate reopen
#     delay 3 -- Allows Spotify window to come to focus
# end tell

# tell application "System Events"
#     tell process "Spotify"
#         -- Trigger Spotify search bar shortcut (Cmd + L)
#         keystroke "l" using command down
#         delay 0.2
        
#         -- Type the song name
#         keystroke "{query}"
#         delay 3 -- Wait for Spotify to fetch search results
        
#         -- Press down key X to play the top matching track
#         repeat {num_of_presses} times
#             key code 125
#             delay 0.2
#         end repeat

#         -- press left key to go to play button
#         key code 123
#         delay 0.2

#         -- press return key to play
#         key code 36
#     end tell
# end tell
# """

    # an additional tab, tab, enter is required for artists, playlists, and albums
    playScript = """
        repeat 2 times
            key code 48
            delay 0.2
        end repeat

        key code 36
    """ if scope != "song" else ""

    script = f"""
tell application "Spotify"
    activate reopen
    delay 5 -- Allows Spotify window to come to focus
end tell

tell application "System Events"
    tell process "Spotify"
        -- Trigger Spotify search bar shortcut (Cmd + L)
        keystroke "l" using command down
        delay 0.2
        
        -- Type the song name
        keystroke "{query}"
        -- press return key to confirm search
        key code 36
        delay 3

        -- press tab twice twice to reach 
        repeat 2 times
            key code 48
            delay 0.2
        end repeat
    end tell

    -- stop current song to ensure this will be played
    tell application "Spotify" to pause

    tell process "Spotify"
        -- Press down key to reach first result and then enter on it
        key code 125
        delay 0.2
        key code 36
        delay 3

        {playScript}
    end tell
end tell
"""

    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# NOTES TRANSLATORS
# ------------------------------------------------------------------------------

def translate_notes_open(action: actions.NotesOpen) -> str:
    """
    Translates notes.open into AppleScript.
    - Brings Notes app forward.
    """
    # Formulate activation command
    return format_as_heredoc("tell application \"Notes\" to activate reopen")

def translate_notes_close(action: actions.NotesClose) -> str:
    """
    Translates notes.close into AppleScript.
    - Shuts down the Notes application.
    """
    # Formulate quit command
    return format_as_heredoc("tell application \"Notes\" to quit")

def translate_notes_get_notes(action: actions.NotesGetNotes) -> str:
    """
    Translates notes.get_notes into AppleScript.
    - Gathers the title names of all stored notes.
    """
    # Build list iteration and formatting script block
    script = """
tell application "Notes"
    set output to ""
    repeat with aNote in every note
        set output to output & name of aNote & linefeed
    end repeat
    return output
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_notes_create_note(action: actions.NotesCreateNote) -> str:
    """
    Translates notes.create_note into AppleScript.
    - Creates a new note with the specified title and body content.
    """
    # Extract content and title arguments
    title = action.params.title
    content = action.params.content
    # Formulate note creation command properties
    script = f"""
tell application "Notes"
    activate
    reopen
    make new note with properties {{name:"{title}", body:"{content}"}}
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_notes_get_note_content(action: actions.NotesGetNoteContent) -> str:
    """
    Translates notes.get_note_content into AppleScript.
    - Retrieves the body content of a note matching the specified title.
    """
    # Extract title query parameter
    title = action.params.title
    # Construct search query returning body text of matching items
    script = f"""
tell application "Notes"
    set matchingNotes to every note whose name is "{title}"
    if (count of matchingNotes) > 0 then
        return body of item 1 of matchingNotes
    else
        return "Note not found"
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE
# "add chicke to the list" as command makes the content "add chicken to the list"
# instead of "chicken" which is expected
def translate_notes_update_note(action: actions.NotesAddToNote) -> str:
    """
    Translates notes.update_note into AppleScript.
    - Appends text to an existing note, or creates one if it doesn't exist.
    """
    # Extract title and append-body arguments
    title = action.params.title
    content = action.params.content
    # Construct script performing HTML appending or fresh note creation
    script = f"""
tell application "Notes"
    activate
    reopen
end tell

tell application "Notes"
    set matchingNotes to every note whose name is "{title}"
    if (count of matchingNotes) > 0 then
        set oldBody to body of item 1 of matchingNotes
        set body of item 1 of matchingNotes to oldBody & "<br>" & "{content}"
    else
        make new note with properties {{name:"{title}", body:"{content}"}}
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# CALENDAR TRANSLATORS
# ------------------------------------------------------------------------------

def translate_calendar_open(action: actions.CalendarOpen) -> str:
    """
    Translates calendar.open into AppleScript.
    - Brings Calendar app to focus.
    """
    # Formulate activation command
    return format_as_heredoc("""
        tell application "Calendar"
            activate 
            reopen
        end tell""")

def translate_calendar_close(action: actions.CalendarClose) -> str:
    """
    Translates calendar.close into AppleScript.
    - Shuts down the Calendar application.
    """
    # Formulate quit command
    return format_as_heredoc("tell application \"Calendar\" to quit")

def translate_calendar_get_events(action: actions.CalendarGetEvents) -> str:
    """
    Translates calendar.get_events into AppleScript.
    - Implements locale-independent dates.
    - Gathers events falling within the 24-hour block of the target date.
    """
    # Parse target date string YYYY-MM-DD in Python
    dt = datetime.strptime(action.params.date, "%Y-%m-%d")
    
    # Construct AppleScript to build a locale-independent targetDate object
    script = f"""
set targetDate to current date
set year of targetDate to {dt.year}
set month of targetDate to {dt.month}
set day of targetDate to {dt.day}
set time of targetDate to 0
set nextDay to targetDate + (24 * hours)

tell application "Calendar"
    set eventList to {{}}
    repeat with aCal in every calendar
        set calEvents to (every event of aCal whose start date is greater than or equal to targetDate and start date is less than nextDay)
        repeat with anEvent in calEvents
            copy (summary of anEvent & " at " & (start date of anEvent as string)) to end of eventList
        end repeat
    end repeat
    return eventList
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)


# KNOWN ISSUE - FIXED IN DATE. YET TO VERIFY
# Duration is 60 minutes always (said 6 to 8 pm)
# Halucinates event name when not told
def translate_calendar_create_event(action: actions.CalendarCreateEvent) -> str:
    """
    Translates calendar.create_event into AppleScript.
    - Implements locale-independent date assembly.
    - Places the event in the default Calendar.
    - Configures extra properties (location, description) if provided.
    """
    # Parse the target date (YYYY-MM-DD) and time (HH:MM) strings in Python
    date_dt = datetime.strptime(action.params.date, "%Y-%m-%d")
    time_parts = [int(p) for p in action.params.time.split(":")]
    
    # Calculate seconds from midnight for the start time setting
    seconds_from_midnight = (time_parts[0] * 3600) + (time_parts[1] * 60)
    
    # Extract duration minutes and convert to integer
    duration_mins = action.params.duration_in_minutes
    
    # Build optional properties values if provided
    optional_props = ""
    if action.params.location:
        optional_props += f', location:"{action.params.location}"'
    if action.params.description:
        optional_props += f', description:"{action.params.description}"'
        
    # Construct locale-independent event creation script
    script = f"""
set startDate to current date
set year of startDate to {date_dt.year}
set month of startDate to {date_dt.month}
set day of startDate to {date_dt.day}
set time of startDate to {seconds_from_midnight}
set endDate to startDate + ({duration_mins} * minutes)

tell application "Calendar"
    activate
    reopen
    delay 1
end tell

tell application "Calendar"
    tell first calendar
        make new event with properties {{summary:"{action.params.title}", start date:startDate, end date:endDate{optional_props}}}
    end tell
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE - FIXED IN DATA. YET TO VERIFY.
# Time updates are not well written. Params need work. Like "duration" isn't used.
# When user says relative times, it will fail because it doesn't know existing times.
def translate_calendar_update_event(action: actions.CalendarUpdateEvent) -> str:
    """
    Translates calendar.update_event into AppleScript.
    - Searches for an event with matching title and updates specified fields.
    - Resolves location, description, dates, times and durations dynamically.
    """
    # Initialize list to hold Python-generated AppleScript line statements
    update_statements = []
    
    # Check if a new date or time requires updating the event start date
    if action.params.date or action.params.time:
        # Construct date update AppleScript block, fetching existing values for missing fields
        date_block = "set newStartDate to start date of targetEvent\n"
        if action.params.date:
            dt = datetime.strptime(action.params.date, "%Y-%m-%d")
            date_block += f"set year of newStartDate to {dt.year}\n"
            date_block += f"set month of newStartDate to {dt.month}\n"
            date_block += f"set day of newStartDate to {dt.day}\n"
        if action.params.time:
            parts = [int(p) for p in action.params.time.split(":")]
            secs = (parts[0] * 3600) + (parts[1] * 60)
            date_block += f"set time of newStartDate to {secs}\n"
            
        date_block += "set start date of targetEvent to newStartDate\n"
        update_statements.append(date_block)
        
    # Check if a new duration needs to be set
    if action.params.duration:
        mins = parse_duration_to_minutes(action.params.duration)
        update_statements.append(f"set end date of targetEvent to (start date of targetEvent) + ({mins} * minutes)")
        
    # Check if location has an update value
    if action.params.location is not None:
        update_statements.append(f'set location of targetEvent to "{action.params.location}"')
        
    # Check if description has an update value
    if action.params.description is not None:
        update_statements.append(f'set description of targetEvent to "{action.params.description}"')
        
    # Join update lines together, prepending tab indentation formatting
    statements_str = "\n        ".join(update_statements)
    
    # Construct search and update execution AppleScript block
    script = f"""
tell application "Calendar"
    set found to false
    repeat with aCal in every calendar
        set matchingEvents to (every event of aCal whose summary is "{action.params.title}")
        if (count of matchingEvents) > 0 then
            set targetEvent to item 1 of matchingEvents
            {statements_str}
            set found to true
            exit repeat
        end if
    end repeat
    if not found then
        return "Event not found"
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)


def translate_calendar_read_event(action: actions.CalendarReadEvent) -> str:
    """
    Translates calendar.read_event into AppleScript.
    - Queries details of events matching title or date constraints.
    """
    # Resolve search properties
    title = action.params.title or ""
    date_str = action.params.date or ""
    
    # Build filter block depending on parameter configurations
    filter_clause = ""
    date_setup = ""
    if title and date_str:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        date_setup = f"""
set targetDate to current date
set year of targetDate to {dt.year}
set month of targetDate to {dt.month}
set day of targetDate to {dt.day}
set time of targetDate to 0
set nextDay to targetDate + (24 * hours)
"""
        filter_clause = 'whose summary is "{title}" and start date is greater than or equal to targetDate and start date is less than nextDay'
    elif title:
        filter_clause = f'whose summary is "{title}"'
    elif date_str:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        date_setup = f"""
set targetDate to current date
set year of targetDate to {dt.year}
set month of targetDate to {dt.month}
set day of targetDate to {dt.day}
set time of targetDate to 0
set nextDay to targetDate + (24 * hours)
"""
        filter_clause = "whose start date is greater than or equal to targetDate and start date is less than nextDay"
    else:
        # Default fallback to listing active events from today if no filter was passed
        filter_clause = "whose start date is greater than or equal to (current date)"
        
    # Construct extraction script returning detailed strings for matched events
    script = f"""
{date_setup}
tell application "Calendar"
    set foundEvents to {{}}
    repeat with aCal in every calendar
        set matching to (every event of aCal {filter_clause})
        repeat with anEvent in matching
            set info to (summary of anEvent & " on " & (start date of anEvent as string))
            try
                set info to info & " at " & location of anEvent
            end try
            try
                set info to info & " - " & description of anEvent
            end try
            copy info to end of foundEvents
        end repeat
    end repeat
    return foundEvents
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# REMINDERS TRANSLATORS
# ------------------------------------------------------------------------------

def translate_reminders_open(action: actions.RemindersOpen) -> str:
    """
    Translates reminders.open into AppleScript.
    - Activates Reminders app.
    """
    # Formulate activation command
    return format_as_heredoc("tell application \"Reminders\" to activate reopen")

def translate_reminders_close(action: actions.RemindersClose) -> str:
    """
    Translates reminders.close into AppleScript.
    - Quits Reminders app.
    """
    # Formulate quit command
    return format_as_heredoc("tell application \"Reminders\" to quit")

def translate_reminders_get_reminders(action: actions.RemindersGetReminders) -> str:
    """
    Translates reminders.get_reminders into AppleScript.
    - Lists active (uncompleted) reminders.
    """
    # Construct list iteration script
    script = """
tell application "Reminders"
    set reminderList to {}
    repeat with aReminder in every reminder whose completed is false
        copy name of aReminder to end of reminderList
    end repeat
    return reminderList
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE
# Didn't convert "Monday" to proper date. Not trained well on it
# Didn't convert "3 days later" to proper date. Not trained well on it
def translate_reminders_create_reminder(action: actions.RemindersCreateReminder) -> str:
    """
    Translates reminders.create_reminder into AppleScript.
    - Implements locale-independent due dates.
    - Configures notes/body and links properties.
    """
    # Initialize variables for date construction
    date_setup = ""
    date_prop = ""
    
    # Process optional due date parameters
    if action.params.date:
        dt = datetime.strptime(action.params.date, "%Y-%m-%d")
        secs = 32400 # 9:00 AM in seconds if no time provided
        if action.params.time:
            parts = [int(p) for p in action.params.time.split(":")]
            secs = (parts[0] * 3600) + (parts[1] * 60)
            
        # Build date setup lines
        date_setup = f"""
set dueDate to current date
set year of dueDate to {dt.year}
set month of dueDate to {dt.month}
set day of dueDate to {dt.day}
set time of dueDate to {secs}
"""
        date_prop = ", due date:dueDate"
        
    # Check for notes content parameters
    notes_prop = ""
    if action.params.notes:
        notes_prop = f', body:"{action.params.notes}"'
        
    # Construct reminder creation script targeting default list
    script = f"""
{date_setup}

tell application "Reminders"
    activate
    reopen
    delay 1
end tell

tell application "Reminders"
    tell default list
        make new reminder with properties {{name:"{action.params.title}"{notes_prop}{date_prop}}}
    end tell
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_reminders_update_reminder(action: actions.RemindersUpdateReminder) -> str:
    """
    Translates reminders.update_reminder into AppleScript.
    - Finds active reminders by title and applies property updates.
    """
    # Initialize list of update statement strings
    update_statements = []
    
    # Handle renaming title properties
    if action.params.new_title:
        update_statements.append(f'set name of targetReminder to "{action.params.new_title}"')
        
    # Handle notes/body updates
    if action.params.new_notes is not None:
        update_statements.append(f'set body of targetReminder to "{action.params.new_notes}"')
        
    # Handle due date updates
    if action.params.new_date or action.params.new_time:
        date_block = "set newDueDate to current date\n"
        if action.params.new_date:
            dt = datetime.strptime(action.params.new_date, "%Y-%m-%d")
            date_block += f"set year of newDueDate to {dt.year}\n"
            date_block += f"set month of newDueDate to {dt.month}\n"
            date_block += f"set day of newDueDate to {dt.day}\n"
        else:
            # Fall back to target reminder's current due date properties if no date is given
            date_block += "try\nset newDueDate to due date of targetReminder\nend try\n"
            
        if action.params.new_time:
            parts = [int(p) for p in action.params.new_time.split(":")]
            secs = (parts[0] * 3600) + (parts[1] * 60)
            date_block += f"set time of newDueDate to {secs}\n"
        else:
            date_block += "set time of newDueDate to 32400\n" # Default 9 AM
            
        date_block += "set due date of targetReminder to newDueDate\n"
        update_statements.append(date_block)
        
    # Join updates statements together
    statements_str = "\n        ".join(update_statements)
    
    # Construct update loop script block
    script = f"""
tell application "Reminders"
    activate
    reopen
    delay 1
end tell

tell application "Reminders"
    set matching to (every reminder whose name is "{action.params.title}" and completed is false)
    if (count of matching) > 0 then
        set targetReminder to item 1 of matching
        {statements_str}
    else
        return "Reminder not found"
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# KNOWN ISSUE:
# Only works if user tells the exact name of the reminder. Which is rare (and stupid)
def translate_reminders_delete_reminder(action: actions.RemindersDeleteReminder) -> str:
    """
    Translates reminders.delete_reminder into AppleScript.
    - Deletes active reminders matching the specified title name.
    """
    # Construct search and delete script block
    script = f"""
tell application "Reminders"
    activate
    reopen
    delay 1
end tell

tell application "Reminders"
    set matching to (every reminder whose name is "{action.params.title}" and completed is false)
    if (count of matching) > 0 then
        delete item 1 of matching
    end if
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# TEXTEDIT TRANSLATORS
# ------------------------------------------------------------------------------

def translate_textedit_open(action: actions.TextEditOpen) -> str:
    """
    Translates textedit.open into AppleScript.
    - Activates TextEdit app.
    """
    # Formulate activation command
    return format_as_heredoc("tell application \"TextEdit\" to activate reopen")

def translate_textedit_close(action: actions.TextEditClose) -> str:
    """
    Translates textedit.close into AppleScript.
    - Quits TextEdit.
    """
    # Formulate quit command
    return format_as_heredoc("tell application \"TextEdit\" to quit")

def translate_textedit_new_document(action: actions.TextEditNewDocument) -> str:
    """
    Translates textedit.new_document into AppleScript.
    - Spawns a new empty text document in TextEdit.
    """
    # Construct document creation script
    script = """
tell application "TextEdit"
    activate
    make new document
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

def translate_textedit_open_document(action: actions.TextEditOpenDocument) -> str:
    """
    Translates textedit.open_document into AppleScript.
    - Opens document at target path.
    - Expands user home directories (~).
    """
    # Expand path structure
    abs_path = os.path.expanduser(action.params.path)
    # Construct file opening command script
    script = f"""
tell application "TextEdit"
    activate
    open POSIX file "{abs_path}"
end tell
"""
    # Return the wrapped heredoc script
    return format_as_heredoc(script)

# ------------------------------------------------------------------------------
# ROUTER TRANSLATORS
# ------------------------------------------------------------------------------

def translate_router_do_nothing(action: actions.RouterDoNothing) -> str:
    """
    Translates router.do-nothing.
    - Returns a shell comment placeholder doing nothing.
    """
    # Return standard shell comment
    return "# Router action: do-nothing"

def translate_router_llm_agent(action: actions.RouterLlmAgent) -> None:
    """
    Translates router.llm-agent actions by starting a background agent execution thread.
    - Spawns the custom LLM agent in a background daemon thread to run concurrently.
    - Plays a verification audio tone asynchronously to confirm initialization of the agent.
    - Returns None as execution bypass to signal that no direct system shell command needs to run immediately.
    
    Technical Details:
    - Extracts the task instruction from the action payload parameters.
    - Uses the background agent's threading engine to trigger the execution queue.
    - Invokes the universal audio utility to execute 'afplay' asynchronously.
    """
    # Extract the natural language prompt or instruction task from the action parameters object
    task_prompt = action.params.task
    # Delegate task prompt processing to the parallel thread starter in the agent module
    agent.start_agent_thread(task_prompt)
    # Return None as execution bypass to signal that no immediate system command execution is queued
    return None

# ==============================================================================
# DISPATCH ROUTING MAP
# ==============================================================================

# Map (app, action) tuples to their respective validation Pydantic classes
ACTION_MODEL_MAP = {
    ("finder", "open"): actions.FinderOpen,
    ("finder", "close"): actions.FinderClose,
    ("finder", "empty_trash"): actions.FinderEmptyTrash,
    ("finder", "get_active_window_path"): actions.FinderGetActiveWindowPath,
    ("finder", "create_folder"): actions.FinderCreateFolder,
    ("system", "set_volume"): actions.SystemSetVolume,
    ("system", "update_volume"): actions.SystemUpdateVolume,
    ("system", "set_brightness"): actions.SystemSetBrightness,
    ("system", "update_brightness"): actions.SystemUpdateBrightness,
    ("system", "read_volume"): actions.SystemReadVolume,
    ("system", "hide_apps"): actions.SystemHideApps,
    ("system", "eject_disks"): actions.SystemEjectDisks,
    ("system", "toggle_dark_mode"): actions.SystemToggleDarkMode,
    ("system", "sleep"): actions.SystemSleep,
    ("system", "shutdown"): actions.SystemShutDown,
    ("system", "restart"): actions.SystemRestart,
    ("system", "lock_screen"): actions.SystemLockScreen,
    # Map the structured system.toggle_wifi action key tuple to its Pydantic validation model class definition.
    ("system", "toggle_wifi"): actions.SystemToggleWifi,
    ("safari", "open"): actions.SafariOpen,
    ("safari", "close"): actions.SafariClose,
    ("safari", "new_tab"): actions.SafariNewTab,
    ("safari", "close_tab"): actions.SafariCloseTab,
    ("safari", "get_active_tab_url"): actions.SafariGetActiveTabURL,
    ("safari", "get_active_tab_title"): actions.SafariGetActiveTabTitle,
    ("safari", "navigate_tab"): actions.SafariNavigateTab,
    ("safari", "refresh"): actions.SafariRefreshPage,
    ("google chrome", "open"): actions.ChromeOpen,
    ("google chrome", "close"): actions.ChromeClose,
    ("google chrome", "new_tab"): actions.ChromeNewTab,
    ("google chrome", "close_tab"): actions.ChromeCloseTab,
    ("google chrome", "get_active_tab_url"): actions.ChromeGetActiveTabURL,
    ("google chrome", "navigate_tab"): actions.ChromeNavigateTab,
    ("google chrome", "refresh"): actions.ChromeRefreshPage,
    ("google chrome", "open_new_window"): actions.ChromeOpenNewWindow,
    ("apple-music", "open"): actions.AppleMusicOpen,
    ("apple-music", "close"): actions.AppleMusicClose,
    ("apple-music", "change_track"): actions.AppleMusicTrackChange,
    ("apple-music", "toggle_playback"): actions.AppleMusicTogglePlayback,
    ("apple-music", "get_playing_song_details"): actions.AppleMusicGetPlayingSongDetails,
    ("apple-music", "add_to_favorites"): actions.AppleMusicAddToFavorites,
    ("apple-music", "remove_from_favorites"): actions.AppleMusicRemoveFromFavorites,
    ("apple-music", "shuffle"): actions.AppleMusicShuffle,
    ("apple-music", "repeat"): actions.AppleMusicRepeat,
    ("spotify", "open"): actions.SpotifyOpen,
    ("spotify", "close"): actions.SpotifyClose,
    ("spotify", "change_track"): actions.SpotifyTrackChange,
    ("spotify", "toggle_playback"): actions.SpotifyTogglePlayback,
    ("spotify", "get_playing_song_details"): actions.SpotifyGetPlayingSongDetails,
    ("spotify", "shuffle"): actions.SpotifyShuffle,
    ("spotify", "repeat"): actions.SpotifyRepeat,
    ("spotify", "search_and_play"): actions.SpotifySearchAndPlay,
    ("notes", "open"): actions.NotesOpen,
    ("notes", "close"): actions.NotesClose,
    ("notes", "get_notes"): actions.NotesGetNotes,
    ("notes", "create_note"): actions.NotesCreateNote,
    ("notes", "get_note_content"): actions.NotesGetNoteContent,
    ("notes", "update_note"): actions.NotesAddToNote,
    ("calendar", "open"): actions.CalendarOpen,
    ("calendar", "close"): actions.CalendarClose,
    ("calendar", "get_events"): actions.CalendarGetEvents,
    ("calendar", "create_event"): actions.CalendarCreateEvent,
    ("calendar", "update_event"): actions.CalendarUpdateEvent,
    ("calendar", "read_event"): actions.CalendarReadEvent,
    ("reminders", "open"): actions.RemindersOpen,
    ("reminders", "close"): actions.RemindersClose,
    ("reminders", "get_reminders"): actions.RemindersGetReminders,
    ("reminders", "create_reminder"): actions.RemindersCreateReminder,
    ("reminders", "update_reminder"): actions.RemindersUpdateReminder,
    ("reminders", "delete_reminder"): actions.RemindersDeleteReminder,
    ("textedit", "open"): actions.TextEditOpen,
    ("textedit", "close"): actions.TextEditClose,
    ("textedit", "new_document"): actions.TextEditNewDocument,
    ("textedit", "open_document"): actions.TextEditOpenDocument,
    ("router", "do-nothing"): actions.RouterDoNothing,
    ("router", "llm-agent"): actions.RouterLlmAgent,
}

# Map (app, action) tuples to their respective translation handler functions
ACTION_TRANSLATOR_MAP = {
    ("finder", "open"): translate_finder_open,
    ("finder", "close"): translate_finder_close,
    ("finder", "empty_trash"): translate_finder_empty_trash,
    ("finder", "get_active_window_path"): translate_finder_get_active_window_path,
    ("finder", "create_folder"): translate_finder_create_folder,
    ("system", "set_volume"): translate_system_set_volume,
    ("system", "update_volume"): translate_system_update_volume,
    ("system", "set_brightness"): translate_system_set_brightness,
    ("system", "update_brightness"): translate_system_update_brightness,
    ("system", "read_volume"): translate_system_read_volume,
    ("system", "hide_apps"): translate_system_hide_apps,
    ("system", "eject_disks"): translate_system_eject_disks,
    ("system", "toggle_dark_mode"): translate_system_toggle_dark_mode,
    ("system", "sleep"): translate_system_sleep,
    ("system", "shutdown"): translate_system_shutdown,
    ("system", "restart"): translate_system_restart,
    ("system", "lock_screen"): translate_system_lock_screen,
    # Map the system.toggle_wifi tuple action key to its translation callback function.
    ("system", "toggle_wifi"): translate_system_toggle_wifi,
    ("safari", "open"): translate_safari_open,
    ("safari", "close"): translate_safari_close,
    ("safari", "new_tab"): translate_safari_new_tab,
    ("safari", "close_tab"): translate_safari_close_tab,
    ("safari", "get_active_tab_url"): translate_safari_get_active_tab_url,
    ("safari", "get_active_tab_title"): translate_safari_get_active_tab_title,
    ("safari", "navigate_tab"): translate_safari_navigate_tab,
    ("safari", "refresh"): translate_safari_refresh_page,
    ("google chrome", "open"): translate_chrome_open,
    ("google chrome", "close"): translate_chrome_close,
    ("google chrome", "new_tab"): translate_chrome_new_tab,
    ("google chrome", "close_tab"): translate_chrome_close_tab,
    ("google chrome", "get_active_tab_url"): translate_chrome_get_active_tab_url,
    ("google chrome", "navigate_tab"): translate_chrome_navigate_tab,
    ("google chrome", "refresh"): translate_chrome_refresh_page,
    ("google chrome", "open_new_window"): translate_chrome_open_new_window,
    ("apple-music", "open"): translate_apple_music_open,
    ("apple-music", "close"): translate_apple_music_close,
    ("apple-music", "change_track"): translate_apple_music_change_track,
    ("apple-music", "toggle_playback"): translate_apple_music_toggle_playback,
    ("apple-music", "get_playing_song_details"): translate_apple_music_get_playing_song_details,
    ("apple-music", "add_to_favorites"): translate_apple_music_add_to_favorites,
    ("apple-music", "remove_from_favorites"): translate_apple_music_remove_from_favorites,
    ("apple-music", "shuffle"): translate_apple_music_shuffle,
    ("apple-music", "repeat"): translate_apple_music_repeat,
    ("spotify", "open"): translate_spotify_open,
    ("spotify", "close"): translate_spotify_close,
    ("spotify", "change_track"): translate_spotify_change_track,
    ("spotify", "toggle_playback"): translate_spotify_toggle_playback,
    ("spotify", "get_playing_song_details"): translate_spotify_get_playing_song_details,
    ("spotify", "shuffle"): translate_spotify_shuffle,
    ("spotify", "repeat"): translate_spotify_repeat,
    ("spotify", "search_and_play"): translate_spotify_search_and_play,
    ("notes", "open"): translate_notes_open,
    ("notes", "close"): translate_notes_close,
    ("notes", "get_notes"): translate_notes_get_notes,
    ("notes", "create_note"): translate_notes_create_note,
    ("notes", "get_note_content"): translate_notes_get_note_content,
    ("notes", "update_note"): translate_notes_update_note,
    ("calendar", "open"): translate_calendar_open,
    ("calendar", "close"): translate_calendar_close,
    ("calendar", "get_events"): translate_calendar_get_events,
    ("calendar", "create_event"): translate_calendar_create_event,
    ("calendar", "update_event"): translate_calendar_update_event,
    ("calendar", "read_event"): translate_calendar_read_event,
    ("reminders", "open"): translate_reminders_open,
    ("reminders", "close"): translate_reminders_close,
    ("reminders", "get_reminders"): translate_reminders_get_reminders,
    ("reminders", "create_reminder"): translate_reminders_create_reminder,
    ("reminders", "update_reminder"): translate_reminders_update_reminder,
    ("reminders", "delete_reminder"): translate_reminders_delete_reminder,
    ("textedit", "open"): translate_textedit_open,
    ("textedit", "close"): translate_textedit_close,
    ("textedit", "new_document"): translate_textedit_new_document,
    ("textedit", "open_document"): translate_textedit_open_document,
    ("router", "do-nothing"): translate_router_do_nothing,
    ("router", "llm-agent"): translate_router_llm_agent,
}

def action_from_json(json_str: str) -> Union[None, object]:
    """
    Parses a raw JSON string and converts it to a validated Pydantic action model.
    
    Technical Details:
    - Parses input using standard json.loads to extract root keys (app, action).
    - Matches keys with ACTION_MODEL_MAP to find the Pydantic class.
    - Resolves and instantiates the specific Pydantic model with strict validation.
    """
    # Parse the input string into a standard dictionary
    data = json.loads(json_str)
    # Retrieve the application name value
    app = data.get("app")
    # Retrieve the action category value
    action = data.get("action")
    
    # Locate the validation model corresponding to keys
    model_cls = ACTION_MODEL_MAP.get((app, action))
    # If no schema is registered, raise a descriptive value error
    if not model_cls:
        raise ValueError(f"No validation schema found for app: '{app}' and action: '{action}'")
        
    # Instantiate the Pydantic model, enforcing type-checks and field validation
    return model_cls.model_validate(data)

def translate_action_to_command(action_obj: object) -> Union[None, str]:
    """
    Directs a validated action object to its specific translator function.
    
    Technical Details:
    - Queries action_obj properties (app, action) to locate the translator method in ACTION_TRANSLATOR_MAP.
    - Executes the corresponding translator, returning a runnable string or None.
    """
    # Retrieve target keys from the validated model instance
    app = getattr(action_obj, "app", None)
    action = getattr(action_obj, "action", None)
    
    # Find matching translator function in mapping registry
    translator_func = ACTION_TRANSLATOR_MAP.get((app, action))
    # If no handler exists, raise value error detailing lack of bridge
    if not translator_func:
        raise ValueError(f"No translation implementation found for app: '{app}' and action: '{action}'")
        
    # Execute the translator passing the Pydantic instance and return the command string
    return translator_func(action_obj)
