"""
This module manages the speech-to-text engine utilizing the Faster-Whisper framework, which is a highly optimized 
re-implementation of OpenAI's Whisper model built on the CTranslate2 engine for efficient transformer execution.
It provides programmatic interfaces for loading Whisper models and executing offline speech-to-text inference 
on raw, linear PCM audio buffers.

Technical Specifications:
- Framework: Faster-Whisper using CTranslate2 backend.
- Hardware Execution: Configured to run on the central processing unit (CPU) utilizing integer 8-bit (int8) quantization.
- Audio Requirements: Pre-processed Float32 single-channel mono PCM audio sampled at a frequency of 16,000 Hz.
- Voice Activity Detection (VAD): Integrated Silero VAD to segment audio streams and ignore non-speech noise.
"""

# Import the warnings system module to programmatically suppress warnings generated during runtime execution
import warnings

# Import the NumPy numerical computing library to manipulate multi-dimensional arrays, perform dtype casting, and handle vector calculations on raw audio buffers
import numpy as np

def load_whisper_model(model_size: str):
    """
    Loads and initializes a Faster-Whisper model instance of a specified capacity (e.g., 'small').
    
    This function is required to initialize the neural network weights from disk into memory,
    applying model quantization (int8) to ensure high computation speeds on CPU resources
    without exceeding standard hardware memory constraints.

    Parameters:
        model_size (str): The size string of the Whisper model to load (typically 'small').

    Returns:
        WhisperModel: An active instance of the loaded Faster-Whisper model ready for speech transcription.
    """
    # Programmatically filter out RuntimeWarning logs generated by the underlying faster_whisper module,
    # specifically ignoring mathematical instability warnings from empty silent frames to prevent user console clutter.
    warnings.filterwarnings("ignore", category=RuntimeWarning, module="faster_whisper")
    
    # Import the WhisperModel class dynamically from the faster_whisper package to defer loading dependencies until execution time
    from faster_whisper import WhisperModel
    
    # Instantiate the WhisperModel object by specifying the model size, targeting the CPU device,
    # and applying 8-bit integer quantization (int8) to minimize RAM usage and optimize matrix operations via CTranslate2.
    model = WhisperModel(model_size, device="cpu", compute_type="int8")
    
    # Return the fully initialized WhisperModel object to the calling function to be cached and reused for transcription tasks
    return model

def transcribe_with_whisper(whisper_model, raw_audio_data: bytes) -> str:
    """
    Performs speech-to-text transcription on raw binary PCM audio bytes using an initialized Faster-Whisper model.
    
    This function is required to normalize incoming raw audio frames, apply Voice Activity Detection (VAD)
    to filter background noise/silence, run beam-search decoding over the transformer's acoustic features,
    and decode the resulting text tokens into a readable English string.

    Parameters:
        whisper_model (WhisperModel): The pre-loaded Whisper model instance used to run inference.
        raw_audio_data (bytes): The raw, 16-bit signed integer (int16) single-channel PCM audio bytes stream.

    Returns:
        str: The final transcribed English text output string.
    """
    # Convert the raw input binary bytes buffer into a 1-D NumPy array of 16-bit signed integers (int16),
    # then normalize the integer values to a float32 decimal range between -1.0 and 1.0 by dividing by 32768.0 (2^15).
    # This step is critical because deep learning acoustic models are mathematically calibrated on normalized float ranges.
    audio_floats = np.frombuffer(raw_audio_data, dtype=np.int16).astype(np.float32) / 32768.0
    
    # Execute the transcription inference process by passing the float array, using a beam search size of 5 for token selection,
    # enabling a Voice Activity Detection (VAD) filter with a minimum silence threshold of 500ms to ignore pauses,
    # and explicitly forcing the decoding language to English to bypass language auto-detection overhead.
    segments, info = whisper_model.transcribe(
        audio_floats,
        beam_size=5,
        vad_filter=True,
        vad_parameters=dict(min_silence_duration_ms=500),
        language="en"
    )
    
    # Iterate over the generated segment generators to extract the text property of each transcript block,
    # join them into a unified space-delimited string, and strip any remaining leading or trailing whitespace.
    transcribed_text = " ".join([segment.text for segment in segments]).strip()
    
    # Return the accumulated, cleaned transcription string to the orchestrator script
    return transcribed_text
